
stages:
  - build
  - package

build-ubuntu-x:
  tags:
    - ubuntu
  stage: build
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq g++ libpcap0.8-dev libx11-dev libxext-dev
    - cd src
    - ln -s vars_x86linux_x11 vars
    - make clean ; make
  artifacts:
    paths:
      - gsplusx
    expire_in: 5 minutes

package-ubuntu-x:
  tags:
    - ubuntu
  stage: package
  artifacts:
    paths:
      - gsplusx


build-ubuntu-sdl:
  tags:
    - ubuntu
  stage: build
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq g++ libpcap0.8-dev libx11-dev libsdl2-dev libfreetype6-dev libsdl2-image-dev
    - cd src
    - ln -s vars_x86linux_sdl vars
    - make clean ; make



build-ubuntu-sdl2:
  tags:
    - ubuntu
  stage: build
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq g++ libpcap0.8-dev libx11-dev libsdl2-dev libfreetype6-dev libsdl2-image-dev
    - cd src
    - ln -s vars_x86linux_sdl2 vars
    - make clean ; make
  artifacts:
    paths:
      - gsplus
    expire_in: 5 minutes

package-ubuntu-sdl2:
  tags:
    - ubuntu
  stage: package
  artifacts:
    paths:
      - gsplus




build-osx:
  tags:
    - osx
  stage: build
  script:
    - cd src
    - ln -s vars_osx_sdl2 vars
    - make clean ; make
  artifacts:
    paths:
      - gsplus
    expire_in: 5 minutes

package-osx:
  tags:
    - osx
  stage: package
  script:
    - chmod +x make_dist_mac.sh
    - ./make_dist_mac.sh
  artifacts:
    paths:
      - gsplus-osx.tar.gz




build-win32:
  tags:
    - windows
  stage: build
  script:
    - cd src
    - ln -s vars_win32 vars
    - make clean
    - make
  artifacts:
    paths:
      - gsplus32.exe
    expire_in: 5 minutes

package-win32:
  tags:
    - windows
  stage: package
  artifacts:
    paths:
      - gsplus32.exe






build-win-sdl:
  tags:
    - windows
  stage: build
  script:
    - cd src
    - ln -s vars_win32_sdl vars
    - make clean
    - make
  artifacts:
    paths:
      - gsplus.exe
    expire_in: 5 minutes

package-win-sdl:
  tags:
    - windows
  stage: package
  artifacts:
    paths:
      - gsplus.exe
