stages:
  - build
  - package

build-ubuntu-x:
  tags:
    - ubuntu
  stage: build
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq g++ libpcap0.8-dev libx11-dev libxext-dev
    - cd src
    - ln -s vars_x86linux_x11 vars
    - make clean ; make
  artifacts:
    paths:
      - gsplusx
    expire_in: 5 minutes

package-ubuntu-x:
  tags:
    - ubuntu
  stage: package
  script:
    - cp src/config.txt .
    - 'echo "\n\n# CI_BUILD_ID: $CI_BUILD_ID" > config.txt'
    - cp COPYING.txt doc/
  artifacts:
    paths:
      - gsplusx
      - config.txt
      - doc/gsplusmanual.txt
      - doc/gsplusmanual.pdf
      - doc/COPYING.txt



build-ubuntu-sdl:
  tags:
    - ubuntu
  stage: build
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq g++ libpcap0.8-dev libx11-dev libsdl2-dev libfreetype6-dev libsdl2-image-dev
    - cd src
    - ln -s vars_x86linux_sdl vars
    - make clean ; make



build-ubuntu-sdl2:
  tags:
    - ubuntu
  stage: build
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq g++ libpcap0.8-dev libx11-dev libsdl2-dev libfreetype6-dev libsdl2-image-dev
    - cd src
    - ln -s vars_x86linux_sdl2 vars
    - make clean ; make
  artifacts:
    paths:
      - gsplus
    expire_in: 5 minutes

package-ubuntu-sdl2:
  tags:
    - ubuntu
  stage: package
  script:
    - cp src/config.txt .
    - 'echo "\n\n# CI_BUILD_ID: $CI_BUILD_ID" > config.txt'
    - cp COPYING.txt doc/
  artifacts:
    paths:
      - gsplus
      - config.txt
      - doc/README.txt
      - doc/gsplusmanual.txt
      - doc/gsplusmanual.pdf
      - doc/COPYING.txt


build-osx:
  tags:
    - osx
  stage: build
  script:
    - cd src
    - ln -s vars_osx_sdl2 vars
    - make clean ; make
  artifacts:
    paths:
      - gsplus
    expire_in: 5 minutes

package-osx:
  tags:
    - osx
  stage: package
  script:
    - 'echo "\n\n# CI_BUILD_ID: $CI_BUILD_ID" > doc/README.txt'
    - chmod +x make_dist_mac.sh
    - ./make_dist_mac.sh
    - chmod +x make_dmg_mac.sh
    - ./make_dmg_mac.sh
  artifacts:
    paths:
      - GSplus-Install.dmg




build-win32:
  tags:
    - windows
  stage: build
  script:
    - cd src
    - ln -s vars_win32 vars
    - make clean
    - make
  artifacts:
    paths:
      - gsplus32.exe
    expire_in: 5 minutes

package-win32:
  tags:
    - windows
  stage: package
  script:
    - cp src/config.txt .
    - 'echo "\n\n# CI_BUILD_ID: $CI_BUILD_ID" > config.txt'
    - cp COPYING.txt doc/
    - cp /bin/cyggcc_s-1.dll .
    - cp /bin/cygstdc++-6.dll	.
    - cp /bin/cygwin1.dll .
    - cp /bin/cygfreetype-6.dll .

  artifacts:
    paths:
      - gsplus32.exe
      - config.txt
      - doc/gsplusmanual.txt
      - doc/gsplusmanual.pdf
      - doc/README.txt
      - doc/COPYING.txt
      - cyggcc_s-1.dll
      - cygstdc++-6.dll
      - cygwin1.dll
      - cygfreetype-6.dll

build-win-sdl:
  tags:
    - windows
  stage: build
  script:
    - cd src
    - ln -s vars_win32_sdl vars
    - make clean
    - make
  artifacts:
    paths:
      - gsplus.exe
    expire_in: 5 minutes

package-win-sdl:
  tags:
    - windows
  stage: package
  script:
    - cp src/config.txt .
    - 'echo "\n\n# CI_BUILD_ID: $CI_BUILD_ID" > config.txt'
    - cp COPYING.txt doc/
    - cp /bin/cyggcc_s-1.dll .
    - cp /bin/cygstdc++-6.dll	.
    - cp /bin/cygwin1.dll .
    - cp /bin/cygfreetype-6.dll .
    - cp /bin/cygbz2-1.dll .
    - cp /bin/cygpng16-16.dll .
    - cp /bin/cygz.dll .
    - cp /bin/cygSDL2-2-0-0.dll .
    - cp /bin/cygSDL2_image-2-0-0.dll .
    - cp /bin/cygjpeg-8.dll .
    - cp /bin/cygtiff-6.dll .
    - cp /bin/cygjbig-2.dll .
    - cp /bin/cyglzma-5.dll .
    - cp /bin/cygwebp-5.dll .



  artifacts:
    paths:
      - gsplus.exe
      - config.txt
      - doc/gsplusmanual.txt
      - doc/gsplusmanual.pdf
      - doc/COPYING.txt
      - doc/README.txt
      - cyggcc_s-1.dll
      - cygstdc++-6.dll
      - cygwin1.dll
      - cygfreetype-6.dll
      - cygbz2-1.dll
      - cygpng16-16.dll
      - cygz.dll
      - cygSDL2-2-0-0.dll
      - cygSDL2_image-2-0-0.dll
      - cygjpeg-8.dll
      - cygtiff-6.dll
      - cygjbig-2.dll
      - cyglzma-5.dll
      - cygwebp-5.dll
