stages:
  - build
  - package



build-ubuntu-x:
  tags:
    - ubuntu
  stage: build
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq g++ libpcap0.8-dev libx11-dev libxext-dev
    - cd src
    - ln -s vars_x86linux_x11 vars
    - make clean ; make
  artifacts:
    paths:
      - gsplusx
    expire_in: 5 minutes

package-ubuntu-x:
  tags:
    - ubuntu
  stage: package
  script:
    - cp src/config.txt .
    - 'echo "# CI_BUILD_ID: $CI_BUILD_ID" >> config.txt'
    - cp LICENSE.txt doc/
  artifacts:
    paths:
      - gsplusx
      - config.txt
      - doc/gsplusmanual.pdf
      - doc/LICENSE.txt




build-ubuntu-sdl:
  tags:
    - ubuntu
  stage: build
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq g++ libpcap0.8-dev libx11-dev libsdl2-dev libfreetype6-dev libsdl2-image-dev
    - cd src
    - ln -s vars_x86linux_sdl vars
    - make clean ; make





build-ubuntu-sdl2:
  tags:
    - ubuntu
  stage: build
  script:
    - sudo apt-get update -qq && sudo apt-get install -y -qq g++ libpcap0.8-dev libx11-dev libsdl2-dev libfreetype6-dev libsdl2-image-dev
    - cd src
    - ln -s vars_x86linux_sdl2 vars
    - make clean ; make
    - mv ../gsplus ../gsplus-ubuntu-sdl
  artifacts:
    paths:
      - gsplus-ubuntu-sdl
    expire_in: 5 minutes

package-ubuntu-sdl2:
  tags:
    - ubuntu
  stage: package
  script:
    - cp src/config.txt .
    - 'echo "# CI_BUILD_ID: $CI_BUILD_ID" >> config.txt'
    - cp LICENSE.txt doc/
    - mv gsplus-ubuntu-sdl gsplus
  artifacts:
    paths:
      - gsplus
      - config.txt
      - doc/README.txt
      - doc/gsplusmanual.pdf
      - doc/LICENSE.txt




build-osx:
  tags:
    - osx
  stage: build
  script:
    - cd src
    - ln -s vars_osx_sdl2 vars
    - make clean ; make
    - mv ../gsplus ../gsplus-osx
  artifacts:
    paths:
      - gsplus-osx
    expire_in: 5 minutes

package-osx:
  tags:
    - osx
  stage: package
  script:
    - mv gsplus-osx gsplus
    - cp src/config.txt .
    - 'echo "# CI_BUILD_ID: $CI_BUILD_ID" >> config.txt'
    - chmod +x make_dist_mac.sh
    - ./make_dist_mac.sh
    - chmod +x make_dmg_mac.sh
    - ./make_dmg_mac.sh
  artifacts:
    paths:
      - GSplus-Install.dmg




build-win32:
  tags:
    - windows
  stage: build
  script:
    - bash -c "cd src; ln -s vars_win32 vars; make clean ; make"
  artifacts:
    paths:
      - gsplus32.exe
    expire_in: 5 minutes

package-win32:
  tags:
    - windows
  stage: package
  script:
    - cp src/config.txt .
    - 'echo "# CI_BUILD_ID: $CI_BUILD_ID" >> config.txt'
    - cp LICENSE.txt doc/
    - cp /bin/cyggcc_s-1.dll .
    - cp /bin/cygstdc++-6.dll	.
    - cp /bin/cygwin1.dll .
    - cp /bin/cygfreetype-6.dll .

  artifacts:
    paths:
      - gsplus32.exe
      - config.txt
      - doc/gsplusmanual.pdf
      - doc/README.txt
      - doc/LICENSE.txt
      - cyggcc_s-1.dll
      - cygstdc++-6.dll
      - cygwin1.dll
      - cygfreetype-6.dll





build-win-sdl2:
  tags:
    - windows
  stage: build
  script:
    - cd src
    - ln -s vars_win32_sdl2 vars
    - make clean
    - make
    - cp parallel.rom ..
    - cp /cygdrive/c/cygwin/bin/cygbz2-1.dll ..
    - cp /cygdrive/c/cygwin/bin/cygfreetype-6.dll ..
    - cp /cygdrive/c/cygwin/bin/cyggcc_s-1.dll ..
    - cp /cygdrive/c/cygwin/bin/cygjpeg-8.dll ..
    - cp /cygdrive/c/cygwin/bin/cygpng16-16.dll ..
    - cp /cygdrive/c/cygwin/bin/cygjpeg-8.dll ..
    - cp /cygdrive/c/cygwin/bin/cygstdc++-6.dll ..
    - cp /cygdrive/c/cygwin/bin/cygwin1.dll ..
    - cp /cygdrive/c/cygwin/bin/cygz.dll ..
    - cp /cygdrive/c/mingw/i686-w64-mingw32/bin/SDL2.dll ..
    - cp /cygdrive/c/mingw/i686-w64-mingw32/bin/SDL2_image.dll ..


  artifacts:
    paths:
      - gsplus.exe
      - parallel.rom
      - cygbz2-1.dll
      - cygfreetype-6.dll
      - cyggcc_s-1.dll
      - cygjpeg-8.dll
      - cygpng16-16.dll
      - cygjpeg-8.dll
      - cygstdc++-6.dll
      - cygwin1.dll
      - cygz.dll
      - SDL2.dll
      - SDL2_image.dll

    expire_in: 5 minutes


package-win-sdl2:
  tags:
    - windows
  stage: package
  script:
    - pwd
    - ls -al
    - cp src/config.txt .
    - 'echo "# CI_BUILD_ID: $CI_BUILD_ID" >> config.txt'
    - cp LICENSE.txt doc/

  artifacts:
    paths:
      - gsplus.exe
      - config.txt
      - doc/gsplusmanual.pdf
      - doc/LICENSE.txt
      - doc/README.txt
      - parallel.rom
      - cygbz2-1.dll
      - cygfreetype-6.dll
      - cyggcc_s-1.dll
      - cygjpeg-8.dll
      - cygpng16-16.dll
      - cygjpeg-8.dll
      - cygstdc++-6.dll
      - cygwin1.dll
      - cygz.dll
      - SDL2.dll
      - SDL2_image.dll
